In [1]:
import torch

In [2]:
import sparse_accumulation_cpp

In [3]:
output = sparse_accumulation_cpp.forward(torch.randn(2, 2), torch.randn(2, 2), 
                                torch.LongTensor([0, 1]), 2, torch.LongTensor([0, 1]), torch.LongTensor([0, 1]))

In [4]:
print(output)

tensor([0., 0.])


In [5]:
import sparse_accumulation

In [6]:
result = sparse_accumulation.SparseAccumulation.apply(torch.randn(2, 2), torch.randn(2, 2), 
                                torch.LongTensor([0, 1]), 2, torch.LongTensor([0, 1]), torch.LongTensor([0, 1]))

In [7]:
print(result)

tensor([0., 0.])


In [8]:
X1 = torch.randn(2, 2)
X2 = torch.randn(2, 2)
X1.requires_grad = True
X2.requires_grad = True
result = sparse_accumulation.SparseAccumulation.apply(X1, X2, 
                                torch.LongTensor([0, 1]), 2, torch.LongTensor([0, 1]), torch.LongTensor([0, 1]))

print(X1.grad)
result.backward(gradient = torch.zeros_like(result))
print(X1.grad)

None
tensor([[0., 0.],
        [0., 0.]])
